copy head.txt+avoid-computer-scratch-rest.html+Last-modified.txt+foot.txt avoid-computer-scratch.php
copy head.txt+backup-rest.html+Last-modified.txt+foot.txt backup.php
copy head.txt+calendar-rest.html+Last-modified.txt+foot.txt calendar.php
copy head.txt+captions-on-pictures-rest.html+Last-modified.txt+foot.txt captions-on-pictures.php
copy head.txt+charts-better-than-excel-rest.html+Last-modified.txt+foot.txt charts-better-than-excel.php
copy head.txt+Command-line-rest.html+Last-modified.txt+foot.txt Command-line.php
copy head.txt+compare-file-rest.html+Last-modified.txt+foot.txt compare-file.php
copy head.txt+compare-files-find-same-lines-rest.html+Last-modified.txt+foot.txt compare-files-find-same-lines.php
copy head.txt+compare-text-files-using-diff-rest.html+Last-modified.txt+foot.txt compare-text-files-using-diff.php
copy head.txt+context-menu-picks-directory-rest.html+Last-modified.txt+foot.txt context-menu-picks-directory.php
copy head.txt+context-menu-underline-rest.html+Last-modified.txt+foot.txt context-menu-underline.php
copy head.txt+CSS-syntax-primer-rest.html+Last-modified.txt+foot.txt CSS-syntax-primer.php
copy head.txt+explorer-crashing-rest.html+Last-modified.txt+foot.txt explorer-crashing.php
copy head.txt+index-rest.html+Last-modified.txt+foot.txt index.php
copy head.txt+Installing-Windows-XP-On-Virtualbox-rest.html+Last-modified.txt+foot.txt Installing-Windows-XP-On-Virtualbox.php
copy head.txt+labels-rest.html+Last-modified.txt+foot.txt labels.php
copy head.txt+locknote-rest.html+Last-modified.txt+foot.txt locknote.php
copy head.txt+mp3-rest.html+Last-modified.txt+foot.txt mp3.php
copy head.txt+notepad-plus-multi-view-rest.html+Last-modified.txt+foot.txt notepad-plus-multi-view.php
copy head.txt+other-rest.html+Last-modified.txt+foot.txt other.php
copy head.txt+pixel-toolbox-rest.html+Last-modified.txt+foot.txt pixel-toolbox.php
copy head.txt+print-document-as-booklet-rest.html+Last-modified.txt+foot.txt print-document-as-booklet.php
copy head.txt+programming-rest.html+Last-modified.txt+foot.txt programming.php
copy head.txt+regex-rest.html+Last-modified.txt+foot.txt regex.php
copy head.txt+screen-capture-rest.html+Last-modified.txt+foot.txt screen-capture.php
copy head.txt+site-map-rest.html+Last-modified.txt+foot.txt site-map.php
copy head.txt+software-edit-rest.html+Last-modified.txt+foot.txt software-edit.php
copy head.txt+software-image-vid-scan-rest.html+Last-modified.txt+foot.txt software-image-vid-scan.php
copy head.txt+Software-new-computer-rest.html+Last-modified.txt+foot.txt Software-new-computer.php
copy head.txt+VBScript-rest.html+Last-modified.txt+foot.txt VBScript.php
copy head.txt+visualization-rest.html+Last-modified.txt+foot.txt visualization.php
copy head.txt+walking-rest.html+Last-modified.txt+foot.txt walking.php
copy head.txt+websites-cloud-rest.html+Last-modified.txt+foot.txt websites-cloud.php
copy head.txt+websites-developing-rest.html+Last-modified.txt+foot.txt websites-developing.php
copy head.txt+websites-managing-rest.html+Last-modified.txt+foot.txt websites-managing.php
copy head.txt+Windows-7-Search-rest.html+Last-modified.txt+foot.txt Windows-7-Search.php
copy head.txt+windows-managing-fi-rest.html+Last-modified.txt+foot.txt windows-managing-fi.php
copy head.txt+windows-managing-sy-rest.html+Last-modified.txt+foot.txt windows-managing-sy.php
copy head.txt+windows-security-rest.html+Last-modified.txt+foot.txt windows-security.php
copy head.txt+winxs-rest.html+Last-modified.txt+foot.txt winxs.php
copy head.txt+yahoo-rest.html+Last-modified.txt+foot.txt yahoo.php
